2014-09-10 14:55:42  [ org.huangxu.data.MinaClient.connectServer(MinaClient.java:39):org.huangxu.data.MinaClient:main:1 ] - [ ERROR ]  请求通信[/192.168.0.143:6602]偶遇异常,堆栈轨迹如下
org.apache.mina.core.RuntimeIoException: Failed to get the session.
	at org.apache.mina.core.future.DefaultConnectFuture.getSession(DefaultConnectFuture.java:58)
	at org.huangxu.data.MinaClient.connectServer(MinaClient.java:36)
	at org.huangxu.data.UserUtil.login(UserUtil.java:35)
	at test.MyTest.main(MyTest.java:48)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at org.apache.mina.transport.socket.nio.NioSocketConnector.finishConnect(NioSocketConnector.java:221)
	at org.apache.mina.transport.socket.nio.NioSocketConnector.finishConnect(NioSocketConnector.java:1)
	at org.apache.mina.core.polling.AbstractPollingIoConnector.processConnections(AbstractPollingIoConnector.java:442)
	at org.apache.mina.core.polling.AbstractPollingIoConnector.access$4(AbstractPollingIoConnector.java:426)
	at org.apache.mina.core.polling.AbstractPollingIoConnector$Connector.run(AbstractPollingIoConnector.java:510)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
